// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2BxCo7Ak0XAZfQjgJhR-LLC1ZZUltkSA',
    appId: '1:819801389589:web:058b9592e54e75d987ec1c',
    messagingSenderId: '819801389589',
    projectId: 'syairbnbclone',
    authDomain: 'syairbnbclone.firebaseapp.com',
    storageBucket: 'syairbnbclone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeY1GQuma1_R1KGnEiWwZ8F0tTCJr0DcU',
    appId: '1:819801389589:android:21ef3a9b1920c9ed87ec1c',
    messagingSenderId: '819801389589',
    projectId: 'syairbnbclone',
    storageBucket: 'syairbnbclone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAzKDRnTKfHsim4dq-1GecljePrF-wn8',
    appId: '1:819801389589:ios:b84fac95de323ab487ec1c',
    messagingSenderId: '819801389589',
    projectId: 'syairbnbclone',
    storageBucket: 'syairbnbclone.firebasestorage.app',
    iosBundleId: 'com.example.syAirbnbClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAzKDRnTKfHsim4dq-1GecljePrF-wn8',
    appId: '1:819801389589:ios:b84fac95de323ab487ec1c',
    messagingSenderId: '819801389589',
    projectId: 'syairbnbclone',
    storageBucket: 'syairbnbclone.firebasestorage.app',
    iosBundleId: 'com.example.syAirbnbClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2BxCo7Ak0XAZfQjgJhR-LLC1ZZUltkSA',
    appId: '1:819801389589:web:6f5017cb2cd636ea87ec1c',
    messagingSenderId: '819801389589',
    projectId: 'syairbnbclone',
    authDomain: 'syairbnbclone.firebaseapp.com',
    storageBucket: 'syairbnbclone.firebasestorage.app',
  );
}
